### ISSUE TITLE
Memory leaking calls

### ISSUE THREAD

**Issue by caffeinepills** [mrJean1/PyCocoa#6] opened 2023-01-31 07:12 UTC
To preface this, we have discovered this issue trying to debug issues with window events on M1 Macs. (Which lead to the initial memory leak discovery #4) During this we have found a memory leak that is exhibited regardless of architecture (Although the M1's seem to be impacted more heavily in terms of behavior).

I have reduced the code to a simple runnable example that exhibits the issue. Essentially we are creating a Window and creating a manual event loop to check for events. The way we check for events is consistent with other libraries (SDL, GLFW, wxPython, etc which involves `dateWithTimeIntervalSinceNow_` and `nextEventMatchingMask_untilDate_inMode_dequeue_` [see example])

1) We have tested with PyObjC and pycocoa. PyObjC does not leak, and the event system does not break down.
(By event system breakdown, what I mean is, events start getting missed. The way we are able to tell with the mousedown and mouse up events, after 100+ clicks or so, events start getting unpredictable. For example, sometimes you will see multiple mouse up events, with no corresponding downs, or vise versa. Seems to only happen to M1 macs.)

PyObjC version: https://pastebin.com/11MFFniA

Pycocoa version: https://pastebin.com/t7ud54C9

These should be identical in terms of calls.

2) On my test machine (non-M1) and my testers (M1), memory usage consistently increases, after minutes it can rise to 250MB+ if not more. I have tried debugging to see if anything specific in Python is growing, but so far I haven't been able to find anything significant. This leads me to believe we are allocating something internally with Cocoa, but it is not getting freed.

3) If we comment out
```py
    while True:
        step(app, 0.0)
```

and use the built in app (`app.run()`) then there are no issues. So this leads me to believe that calls to cocoa from Python are not properly getting freed in some manner. 

I am not too familiar with cocoa, objc, or objective C myself, so I am not quite sure what further testing needs to be done. Any input or what I can do to further track this down would be appreciated.

**Comment by mrJean1** [comment] 2023-01-31 14:35
Thank you for reporting the issues and examples.  Will be investigating next week.

**Comment by caffeinepills** [comment] 2023-02-02 04:43
Just mentioning I ran leaks on MacOS and it shows many things like this: 
```Leak: 0x7fc1896ff940  size=272  zone: MallocHelperZone_0x10cd0d000   _NSDeallocObserver  ObjC  libobjc.A.dylib
Leak: 0x7fc1896ffa50  size=272  zone: MallocHelperZone_0x10cd0d000   _NSDeallocObserver  ObjC  libobjc.A.dylib
Leak: 0x7fc1896ffb60  size=272  zone: MallocHelperZone_0x10cd0d000   _NSDeallocObserver  ObjC  libobjc.A.dylib
Leak: 0x7fc1896ffc70  size=272  zone: MallocHelperZone_0x10cd0d000   _NSDeallocObserver  ObjC  libobjc.A.dylib
Leak: 0x7fc1896ffd80  size=272  zone: MallocHelperZone_0x10cd0d000   _NSDeallocObserver  ObjC  libobjc.A.dylib
```

In runtime I set `cached=False`, then the leaks no longer occur. I still don't have access yet to check if this fixes M1 at all, but something worth mentioning.

**Comment by mrJean1** [comment] 2023-02-02 05:37
The leaks occur in `ObjCInstance` where an `_NSDeallocObserver` is created for each _cached_ Python-wrapped ObjC instance.  There may still be an issue in the caching logic or caching may not be necessary for any wrapped ObjC object _other than those required for callbacks from ObjC into Python_.  Your examples are very helpful to get to the bottom of this.

**Comment by mrJean1** [comment] 2023-02-02 22:46
PyCocoa [23.02.03](https://github.com/mrJean1/PyCocoa) contains several other changes to prevent the memory leaks reported above and earlier in issue #4.

Attached a slightly modified version PyCocoa test case on PasteBin.  Running that with _PyCocoa 23.02.03_ does not show any memory leaks (on macOS 13.1 Ventura, Apple Si M1 and Python 3.11.1).  The setting of `ObjCInstance` keyword argument `cached=True` is unchanged.

[issue6.zip](https://github.com/mrJean1/PyCocoa/files/10574055/issue6.zip)

**Comment by caffeinepills** [comment] 2023-02-03 05:08
Thanks for looking at this. I did do some testing, and while initially it appeared the issue was fixed. I was able to reproduce it by changing back to a faster timeout and for it to exit after a minute, you can see the memory usage grow in that minute.

```py
    alive = True
    i = 0

    t = time.time()

    while alive:
        i += 1
        if time.time() - t > 60:
            alive = False

        step(app, 0.0, i)
```

The memory leak does seem slower than before, but it is still leaking unfortunately. I can confirm though that the objc instances  are stable and doesn't grow much higher than around 45-47.

That being said, I am not 100% convinced this is pool related anymore.

Using the MacOS leaks program there is a flag (--autoreleasePools) which states `print contents of autorelease pools, by thread`.

Using this I received the following (with a long long long list of what is in each pool) using the default `app.run` and memory stayed around 22 MB:
```
Physical footprint:         20.9M
Physical footprint (peak):  21.0M
----

Entries held only by autorelease pools are marked with **

                     Total entries in autoreleasepools:      1454
                    Unique entries in autoreleasepools:       954

         Memory size of autoreleasepool content blocks:         6 blocks       24K bytes
        Memory directly held only by autorelease pools:       650 blocks       32K bytes
      Memory indirectly held only by autorelease pools:       192 blocks       14K bytes
                                                           ======           ======
  Total memory of autorelease pools and content blocks:       848 blocks       70K bytes


```

When using the leaking version and letting it grow to 600 MB:

```
Physical footprint:         621.3M
Physical footprint (peak):  621.3M
----

Entries held only by autorelease pools are marked with **

                     Total entries in autoreleasepools:      1458
                    Unique entries in autoreleasepools:       957

         Memory size of autoreleasepool content blocks:         3 blocks       12K bytes
        Memory directly held only by autorelease pools:       640 blocks       31K bytes
      Memory indirectly held only by autorelease pools:       169 blocks       12K bytes
                                                           ======           ======
  Total memory of autorelease pools and content blocks:       812 blocks       55K bytes

```

As you can see, there is not really that much difference in terms of pool usage. (Atleast from what this leaks program reports)

**Comment by mrJean1** [comment] 2023-02-03 17:55
Indeed, there is a slow memory leak somewhere.  Attached is another version of `issue6.py` which prints the peak memory usage of the process whenever that increases.

It also shows the delta, which is usually 16 KB on M1.  It may also be the default [memory allocation](https://docs.python.org/3/c-api/memory.html#default-memory-allocators) in Python.  Running with
```
% env  PYTHONMALLOCSTATS=1  python3  issue6p.py
```
stops at step 957 when Python allocates an additional _arena_ after the initial 6.  The stats are include as `issue6stats.txt`.

Comparing the details of the last two, 7 and 6 is not obvious.  For example, the `Total bytes in arenas` increased from 6,291,456 to 7,340,032.  However, there are `255 unused pools * 16384 or 3,686.,400 bytes` in the last one?

[issue6p_stats.zip](https://github.com/mrJean1/PyCocoa/files/10581476/issue6p_stats.zip)

**Comment by caffeinepills** [comment] 2023-02-04 05:15
This memory management stuff is a little over my head, but I can just go over what else I have been testing.

While running your code it takes a bit for the memory leak to start printing, I can confirm one thing that makes it rapidly increase is just moving the mouse in the window. I assume that it is returning a bunch of events for the mouse motion. This occurs with the pyobjc version as well, and both experience memory leaks during this process. 

Onto your example with the increasingly large timeouts with PYTHONMALLOCSTATS=1. I get similar results with it, however again, I am not too experienced in memory management stuff, so I am not sure if it's pointing us in the right direction.

I will say that with pyobjc (using your resource code and increasing timeout count and PYTHONMALLOCSTATS) I get worse memory management. Which is odd because with the desired behavior of an infinite event loop and 0.0, it's actually LESS memory usage. I am not sure if it's just the result of the malloc stats doing something, but definitely the opposite result of what I'd expect.

Further testing, I set the loop to 100000 and 0.0 timeout, and got very different results:

pyobjc: 100,000 iterations, 0.0 timeout, run normally.
```py
1 42.605 44675072
2 42.98 393216
346 42.984 4096
3894 43.0 16384
25851 43.004 4096
Terminated quickly
```

pyobjc: 100,000 iterations, 0.0 timeout, PYTONMALLOCSTATS
```
1 46.145 48386048
2 46.508 380928
108 46.523 16384
385 46.945 442368
386 47.703 794624
624 47.809 110592
2429 47.848 40960
2430 47.863 16384
2549 48.004 147456
3781 49.293 1351680
3782 49.457 172032
3792 49.461 4096
3843 49.465 4096
11479 49.914 471040
Terminated quickly
```


pycocoa: 100,000 iterations, 0.0 timeout, run normally.
```py
1 45 29.844 31293440
2 45 29.98 143360
6 45 29.988 8192
7 45 30.0 12288
8 45 30.02 20480
9 45 30.027 8192
10 45 30.043 16384
11 45 30.051 8192
12 45 30.062 12288
13 45 30.078 16384
24 45 30.082 4096
25 45 30.094 12288
26 45 30.098 4096
28 45 30.102 4096
34 45 30.109 8192
38 45 30.113 4096
43 45 30.117 4096
... <more but continued for a long time and took a long time to terminate>
```
This is constantly printing as it is increasing rapidly. 

pycocoa: 100,000 iterations, 0.0 timeout, PYTONMALLOCSTATS
```
14 45 33.434 20480
26 45 33.438 4096
27 45 33.441 4096
39 45 33.449 8192
47 45 33.457 8192
62 45 33.461 4096
63 45 33.465 4096
77 45 33.469 4096
88 45 33.473 4096
90 45 33.477 4096
92 45 33.48 4096
99 45 33.484 4096
107 45 33.488 4096
121 45 33.492 4096
133 45 33.496 4096
136 45 33.5 4096
153 45 33.504 4096
... <more but continued for a long time and took a long time to terminate>
```

I am not sure why the pyobjc terminates much faster, but maybe due to the nature of pyobjc being compiled, I have no idea, just something I observed.

Some tests with yours:
pycocoa: 1k iterations, ms * 1e-3 timeout, run normally
```
1 45 29.863 31313920
2 45 29.988 131072
6 45 30.0 12288
7 45 30.012 12288
8 45 30.031 20480
9 45 30.035 4096
10 45 30.055 20480
11 45 30.059 4096
12 45 30.184 131072
13 45 30.32 143360
23 45 30.332 12288
24 45 30.34 8192
33 45 30.348 8192
41 45 30.352 4096
49 45 30.359 8192
53 45 30.363 4096
54 45 30.367 4096
76 45 30.371 4096
87 45 30.375 4096
88 45 30.379 4096
94 45 30.383 4096
95 45 30.387 4096
96 45 30.391 4096
98 45 30.395 4096
139 45 30.398 4096
... <more but continued for a long time and took a long time to terminate>
```


pyobjc 1k iterations, ms * 1e-3 timeout, run normally
```
1 42.629 44699648
2 43.0 389120
6 43.004 4096
13 43.023 20480
33 43.027 4096
68 43.031 4096
172 43.102 73728
228 43.105 4096
229 43.109 4096
```
This basically sat frozen on 229 until I started moving the mouse in the window and then started rapidly changing:
```
244 43.113 4096
275 44.094 1028096
276 44.324 241664
293 45.398 1126400
294 45.406 8192
295 45.629 233472
301 45.633 4096
316 45.637 4096
326 45.641 4096
336 45.66 20480
```

I am not sure what to make of things, but the behavior is definitely different between the two using the same supposed code.

**Comment by mrJean1** [comment] 2023-02-04 08:04
`PyObj` is a complete bridge between Phython and Objective-C, but `pycocoa` provides access to only a handful of Objective-C functionality.  It makes sense that the `PyObj` and `pycocoa` versions exhibit different memory usage.

The core of this particular example is the `step` function: it allocates a few objects in a pool and then deletes all those … over and over.  The Python memory manager allocates more and more memory for each `step` invokation and hangs on to any freed memory.  At some point, freed memory will be re-used and/or returned to the underlying operating system resulting in the final peak usage.

This is not a leak, this is expected behavior, IMO.  If it were a leak both `PyObj` and `pycocoa` will crash when the process’ memory is limit is reached.   But that will not occur, both will keep running indefinitely.  Try using Python’s `resource.setrlimit` or the `ulimit` shell command to set a or several memory limits (to say 25 MB for `pycocoa`).

**Comment by caffeinepills** [comment] 2023-02-04 08:45
I can understand the difference between the two being just how they are implemented.

As far as the step function, even if that was the case of it being Python, it still doesn't explain why not using the dealloc observer drastically reduces the leak. Unless you are saying every call to hard retain through `objc_setAssociatedObject` is allocating something in Python that is waiting to be re-used?

It also doesn't explain why the events start to break down after 100-ish amount of clicks, which to me sounded more like some memory building up causing the issues. Although that issue may not be related.  I was hoping finding a resolution to the memory leak would fix the event issue, but if it can't be resolved then that can be considered a separate issue.

I can create a separate issue for that, but maybe you can confirm the results I am seeing, but eventually after 100+ clicks on an M1 processor, the events start acting up. You can test this with the original example, eventually getting impossible (I don't know if it's missed or duplicate) events such as double down or up events:
```py
got mouse down (180, 150)
got mouse up (180, 150)
got mouse down (180, 150)
got mouse down (180, 150)
got mouse up (180, 150)
got mouse down (180, 150)
got mouse down (180, 150)
got mouse up (180, 150)
got mouse down (180, 150)
got mouse up (180, 150)
```

If you minimize the window then maximize it again, it seems to work for a bit then breaks again. Could you confirm such an issue on your end?

**Comment by mrJean1** [comment] 2023-02-04 15:14
Correct.  To be more specific, the memory used by the Python representation of de-allocated Objective-C objects is kept by Python until re-used some time later.  Objective-C likely does the same inside its memory manager with released objects.  That is not a leak, that is typical behavior of Python’s and most memory managers.  The periodic increases seen in the example may not all be due to Python.

The event breakdown is a separate issue.

**Comment by caffeinepills** [comment] 2023-02-04 15:41
I think I may have a solution to this issue.

So one way to look at is, objects hard observed are not getting the dealloc callback for whatever reason. So one solution could be breaking the association. [I have found these here that setting it to None is the correct way to deassociate an object.](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocAssociativeReferences.html) 

If I add `_observer` and then to set the observer ref we would do this in the `__new__` of `ObjCInstance`.:
```py
class ObjCInstance(_ObjCBase):
    '''Python wrapper for an ObjC instance.
    '''
    _autoPool   = 0
    _dealloc_d  = False
    _from_py2NS = False
    _objc_cache = {}  # see _NSDeallocObserver, example class_wrapper4.py
    _objc_class = None
    _objc_ptr   = None  # shut PyChecker up
    _retained   = None
    _observer   = None

    def __new__(cls, objc_ptr, cached=True):
        '''New L{ObjCInstance} or a previously created, cached one.

           @param objc_ptr: The ObjC instance (L{Id_t} or C{c_void_p}).
           @keyword cached: Cache the new instance (C{bool}).
        '''
        # Make sure that obj_ptr is wrapped in an Id_t.
        if not isinstance(objc_ptr, Id_t):
            objc_ptr = cast(objc_ptr, Id_t)

        ptr = objc_ptr.value  # actual ObjC address
        if not ptr:
            return None  # nil pointer

        if cached:
            # Check if we've already created an ObjCInstance for this
            # Id_t(objc_ptr) and if so, return it.  Otherwise, create
            # an ObjCInstance any object pointer first encountered.
            # That ObjCInstance will persist until the object is de-
            # allocated by ObjC, see _ns/NSDeallocObserver below.
            try:
                # cls._objc_cache == ObjCInstance._objc_cache
                return cls._objc_cache[ptr]
            except KeyError:
                pass

        # Otherwise, create a new ObjCInstance.
        self = super(ObjCInstance, cls).__new__(cls)  # objc_instance
        self._objc_ptr = self._as_parameter_ = objc_ptr  # for ctypes

        # Determine and hold the class of this object.
        self._objc_class = NS_ = ObjCClass(get_classof(objc_ptr))

        _ObjC_log(self, 'new', 'I')

        if cached:
            # store new object in the dictionary of cached objects,
            # keyed by the (integer) memory address pointed to by the
            # obj_ptr (cls._objc_cache == ObjCInstance._objc_cache)
            cls._objc_cache[ptr] = self
            if not isClass(self):
                # observe the objc_ptr.value, the
                # key into the _objc_cache dict
                self._observer = _nsDeallocObserver(ptr)

            auto = _NSAutorelease.Pools
            if NS_ is _NSAutorelease.Pool:
                # i.e. isObjCInstanceOf(self, _NSAutoreleasePool)
                self._autoPool = _NSAutorelease.Pools = auto + 1
            elif auto:
                self._autoPool = auto

        # print('new', self, cached, self.inPool, self.objc_classname)
        return self
```



And then change cache clear to break the association if we never got a dealloc:
```py
    def _cache_clear(self):
        if self._objc_class is _NSAutorelease.Pool:
            # i.e. isObjCInstanceOf(self, NSAutoreleasePool)
            cache, retained, auto = self._objc_cache, {}, self.inPool
            # self._cache_print('cached')
            while cache:
                ptr, objc = cache.popitem()
                if objc.retained() or objc.inPool < auto:
                    retained[ptr] = objc
                else:
                    if not objc._dealloc_d:
                        libobjc.objc_setAssociatedObject(objc._objc_ptr, objc._observer, None, 0)
                        send_message(objc._objc_ptr, 'release')
            cache.update(retained)
            # self._cache_print('retained')
            _NSAutorelease.Pools = max(0, auto - 1)
```

The leak seems much slower after that. Even at 75k and 150k iterations the memory usage seems good: 
```
74489 45 30.977 4096
150626 45 30.992 16384
```

**Comment by mrJean1** [comment] 2023-02-04 16:14
Great point!  However, instead of holding the `_nsDeallocObserver `, do not create an `_nsDeallocObserver` for objects allocated in an `NSAutoreleasePool`.  Something like
```
        if cached:
            # store new object in the dictionary of cached objects,
            # keyed by the (integer) memory address pointed to by the
            # obj_ptr (cls._objc_cache == ObjCInstance._objc_cache)
            cls._objc_cache[ptr] = self

            auto = _NSAutorelease.Pools
            if NS_ is _NSAutorelease.Pool:
                # i.e. isObjCInstanceOf(self, _NSAutoreleasePool)
                self._autoPool = _NSAutorelease.Pools = auto + 1
            elif auto:
                self._autoPool = auto
            elif not isClass(self):
                # observe the objc_ptr.value, the
                # key into the _objc_cache dict
                self._observer = _nsDeallocObserver(ptr)
```
Because, objects in an `NSAutoreleasePool` never receive the `dealloc` and `finalize` message.

**Comment by caffeinepills** [comment] 2023-02-04 17:14
That sounds like that may work too as long as there is not a case where you would create something that needs to be retained inside the autorelease pool.

**Comment by mrJean1** [comment] 2023-02-04 18:28
Objects allocated within an `NSAutoreleasePool` are no longer cached and no longer "`_NSDeallocObserved`" in `pycocoa` (except for the `NSAutoreleasePool` instance itself).

If such a pooled object is retained, the assumption is that it will be removed from the pool or not be released by a `pool.drain`, whatever.  Regardless, since the Python object is not cached that object will persist (until it leaves Python scope) and can not create a leak.

All this complexity would be unnecessary if objects allocated in an `NSAutoreleasePool` did get a `dealloc` message when the pool is drained.

Again, thank you for all your effort and persistance to get to the very bottom of this issue.  Please close it.

**Comment by caffeinepills** [comment] 2023-02-04 18:37
> All this complexity would be unnecessary if objects allocated in an NSAutoreleasePool did get a dealloc message when the pool is drained.

Agreed. What's interesting is this was probably the case that you would always get a dealloc back when this was initially written in python-cocoa, but recent MacOS's have changed things to the point where it's not longer a guarantee. 

Appreciate looking into these issues with me.  I will go ahead and close this.

**Comment by mrJean1** [comment] 2023-02-04 21:24
In `pycocoa`, the `NSAutoreleasePool` usage was never investigated before this issue.  The current documentation states that objects allocated in an `NSAutoreleasePool` all receive an [autorelease and release message](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmAutoreleasePools.html#//apple_ref/doc/uid/20000047-CJBFBEDI).  That may happen, but those objects never get the `dealloc` one.  It may have to do with `reference-counting` vs `garbage collecting` memory managers, [see here](https://developer.apple.com/documentation/foundation/nsautoreleasepool/1807014-release).

**Comment by mrJean1** [comment] 2023-02-05 20:32
A few other updates in release [23.02.05](https://github.com/mrJean1/PyCocoa).  In particular logging of `ObjCInstance.__del__` calls and draining on `NSAutoreleasePool`s.  More information about logging in the documentation of module [pycocoa.runtime](https://mrjean1.github.io/PyCocoa/pycocoa.runtime-module.html).

**Comment by caffeinepills** [comment] 2024-09-09 21:39
Just thought I'd mention one small issue I've run into as well. If you want to manually release something, and overwrite behavior for the `dealloc` function, this cannot be done with this method.

For example, if I have a delegate and I want to remove the retain and then release it so I can create a new one. I would do:
```py
import ctypes
import time

from pycocoa import *

class AutoReleasePool:
    def __enter__(self):
        self.pool = NSAutoreleasePool.alloc().init()
        return self.pool

    def __exit__(self, exc_type, exc_value, traceback):
        self.pool.drain()
        del self.pool

class _View_Implementation(object):
    _View = ObjCSubclass('NSView', '_View')

    @_View.method(b'@' + PyObjectEncoding * 1)
    def initWithFrame_(self, frame):
        objc = ObjCInstance(send_super(self, 'initWithFrame:', frame))
        return objc  # objc is self


_View = ObjCClass('_View')  # the actual class


class _Delegate_Implementation(object):
    _Delegate = ObjCSubclass('NSObject', '_Delegate')

    @_Delegate.method(b'@' + PyObjectEncoding)
    def init(self, app):
        objc = ObjCInstance(send_super(self, 'init'))
        self._app = app
        return objc  # objc is self

    @_Delegate.method('v')
    def dealloc(self):
        self._app = None
        print("DEALLOCED!", self._retained)  # Set again!
        send_super(self, 'dealloc')

    @_Delegate.method(b'v@')
    def windowWillClose_(self, notification):
        self._app.terminate_(self)


_Delegate = ObjCClass('_Delegate')  # the actual class


def kill(obj_instance):
    print(obj_instance)
    obj_instance.retained(False)
    print("Retained", obj_instance._retained)
    obj_instance.release()
    print("Retained", obj_instance._retained)


def main():
    app = NSApplication.sharedApplication()

    with AutoReleasePool():
        frame = NSMakeRect(200, 200, 480, 320)
        window = NSWindow.alloc().initWithContentRect_styleMask_backing_defer_(
            frame, NSWindowStyleMaskUsual,
            NSBackingStoreBuffered,
            False)

        view = _View.alloc().initWithFrame_(frame, 11)
        window.setContentView_(view)

        delegate = _Delegate.alloc().init(app)
        window.setDelegate_(delegate)

        window.display()
        window.orderFrontRegardless()

        kill(delegate)

    print("Is still in there:", delegate in ObjCInstance._objc_cache.values())


main()
```

What ends up happening is once `dealloc` is called by the OS, it will either remake the `ObjCInstance` (if you cleared it from cache), or use the existing one. Either way, the `ObjCSubclass.method` will automatically sets the instance back to `retained=True`. If it was removed from the cache, it ends up getting put back as well. If you comment out the dealloc, it works as intended. I'm sure it's not very common, but thought I'd mention it.

**Closed** 2024-09-21 21:37 UTC
